
###########################################################
# GENERATED FILE. DO NOT EDIT
# Generated by stackato-ops/dev-tools/gemlocker/gemlocker
###########################################################

source (ENV['RUBYGEMS_MIRROR'] or 'https://rubygems.org')

ruby '1.9.3' # prevents hard-to-diagnose errors with bundle install

gem 'addressable'       ,    '2.2.8'
gem 'bcrypt-ruby'       ,    '2.1.4'
gem 'beefcake'          ,    '0.3.7'
gem 'builder'           ,    '3.2.0', :groups => [:test]
gem 'ci_reporter'       ,    '1.8.4', :groups => [:test]
gem 'cookiejar'         ,    '0.3.0'
gem 'curb'              ,   '0.7.18'
gem 'daemons'           ,    '1.1.9'
gem 'data_objects'      ,  '0.10.13'
gem 'datamapper'        ,    '1.1.0'
gem 'diff-lcs'          ,    '1.2.4', :groups => [:test]
gem 'dm-aggregates'     ,    '1.1.0'
gem 'dm-constraints'    ,    '1.1.0'
gem 'dm-core'           ,    '1.1.0'
gem 'dm-do-adapter'     ,    '1.1.0'
gem 'dm-migrations'     ,    '1.1.0'
gem 'dm-serializer'     ,    '1.1.0'
gem 'dm-sqlite-adapter' ,    '1.1.0'
gem 'dm-timestamps'     ,    '1.1.0'
gem 'dm-transactions'   ,    '1.1.0'
gem 'dm-types'          ,    '1.1.0'
gem 'dm-validations'    ,    '1.1.0'
gem 'do_sqlite3'        ,  '0.10.13'
gem 'docopt'            ,    '0.5.0'
gem 'em-hiredis'        ,    '0.2.1'
gem 'em-http-request'   ,    '1.0.3'
gem 'em-socksify'       ,    '0.2.1'
gem 'eventmachine'      ,    '1.0.1'
gem 'eventmachine-tail' ,    '0.6.4'
gem 'eventmachine_httpserver',    '0.2.1'
gem 'fastercsv'         ,    '1.5.5'
gem 'fraggle'           ,    '4.0.1'
gem 'fraggle-block'     ,    '0.2.0'
gem 'hiredis'           ,    '0.4.5'
gem 'http_parser.rb'    ,    '0.5.3'
gem 'ipaddress'         ,    '0.8.0'
gem 'json'              ,    '1.4.6'
gem 'json_pure'         ,    '1.8.0'
gem 'mono_logger'       ,    '1.1.0'
gem 'multi_json'        ,    '1.7.4', :groups => [:test]
gem 'mustache'          ,   '0.99.4'
gem 'nats'              ,   '0.4.26'
gem 'net-ssh'           ,    '2.6.7'
gem 'pg'                ,   '0.14.1'
gem 'posix-spawn'       ,    '0.3.6'
gem 'rack'              ,    '1.5.2'
gem 'rack-protection'   ,    '1.5.0'
gem 'rake'              ,    '0.9.6', :groups => [:test, :default]
gem 'redis'             ,    '3.0.4'
gem 'redis-namespace'   ,    '1.3.0'
gem 'resque'            ,   '1.24.1'
gem 'resque-status'     ,    '0.4.1'
gem 'rspec'             ,   '2.13.0', :groups => [:test]
gem 'rspec-core'        ,   '2.13.1', :groups => [:test]
gem 'rspec-expectations',   '2.13.0', :groups => [:test]
gem 'rspec-mocks'       ,   '2.13.1', :groups => [:test]
gem 'ruby-hmac'         ,    '0.4.0'
gem 'ruby-termios'      ,    '0.9.6'
gem 'simplecov'         ,    '0.7.1', :groups => [:test]
gem 'simplecov-html'    ,    '0.7.1', :groups => [:test]
gem 'simplecov-rcov'    ,    '0.2.3', :groups => [:test]
gem 'sinatra'           ,    '1.3.6'
gem 'sqlite3'           ,    '1.3.7'
gem 'stackato-kato'     ,   '2.11.0'
gem 'stringex'          ,    '1.2.2'
gem 'term-ansicolor'    ,    '1.0.7'
gem 'thin'              ,    '1.5.1'
gem 'tilt'              ,    '1.4.1'
gem 'uuidtools'         ,    '2.1.4'
gem 'vcap_common'       ,   '1.0.12', :path => '../../common', :require => ['vcap/common', 'vcap/component', 'vcap/util']
gem 'vcap_logging'      ,    '1.0.1', :require => ['vcap/logging']
gem 'vcap_services_base',   '0.1.10', :path => "../base"
gem 'vegas'             ,   '0.1.11'
gem 'vic'               ,    '1.0.0'
gem 'xmlparser'         ,  '0.7.2.1'
gem 'yajl-ruby'         ,    '1.1.0'

